version: '3.8'

services:
  # 1. Сервис базы данных PostgreSQL
  postgres:
    image: postgres:16.9
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    # проверка healthcheck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Django
  web:
    build:
      context: .
    environment:
      DB_PASS: ${DB_PASS}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_HOST: postgres
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - django_static:/usr/src/app/static

  # 3. Nginx
  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - django_static:/var/www/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  django_static:


